// Copyright (c) The Nexus-Node Contributors
// SPDX-License-Identifier: Apache-2.0

//! `nexus-genesis` — CLI tool for generating the Nexus genesis configuration.
//!
//! Produces a signed genesis configuration JSON file given validator public
//! key bundles and chain parameters. The resulting file is loaded by
//! `nexus-node` at first boot to initialise the chain state.
//!
//! # Usage
//!
//! ```text
//! # Generate from validator key bundles:
//! nexus-genesis generate \
//!     --chain-id nexus-testnet-1 \
//!     --num-shards 4 \
//!     --stake 1000000000 \
//!     --validator-keys ./validator-0/validator-public-keys.json \
//!     --validator-keys ./validator-1/validator-public-keys.json \
//!     --validator-keys ./validator-2/validator-public-keys.json \
//!     --validator-keys ./validator-3/validator-public-keys.json \
//!     --output genesis.json
//!
//! # Validate an existing genesis file:
//! nexus-genesis validate --input genesis.json
//!
//! # Generate a minimal test genesis:
//! nexus-genesis test-genesis --output genesis.json
//! ```

#![forbid(unsafe_code)]

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use nexus_config::{ConsensusConfig, GenesisConfig, GenesisValidatorEntry};
use nexus_primitives::{Amount, ShardId, TimestampMs};
use serde::Deserialize;

// ── CLI definitions ──────────────────────────────────────────────────────

/// Nexus genesis configuration generator.
///
/// Creates the initial chain configuration file that bootstraps the validator
/// set, token allocations, and consensus parameters.
#[derive(Parser)]
#[command(name = "nexus-genesis", version, about)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate a genesis configuration from validator key bundles.
    Generate {
        /// Unique chain identifier (e.g., "nexus-testnet-1").
        #[arg(long)]
        chain_id: String,

        /// Number of execution shards.
        #[arg(long, default_value = "4")]
        num_shards: u16,

        /// Default stake per validator (NXS base units).
        #[arg(long, default_value_t = Amount::ONE_NXS.0)]
        stake: u64,

        /// Paths to validator-public-keys.json files (one per validator).
        #[arg(long = "validator-keys", required = true)]
        validator_keys: Vec<PathBuf>,

        /// Optional custom validator names (in same order as --validator-keys).
        #[arg(long = "validator-name")]
        validator_names: Vec<String>,

        /// Libp2p PeerIds (base58), one per validator, same order as --validator-keys.
        /// Generated by `nexus-keygen identity`.
        #[arg(long = "network-peer-id", required = true)]
        network_peer_ids: Vec<String>,

        /// Genesis timestamp in milliseconds since epoch (0 = now).
        #[arg(long, default_value = "0")]
        timestamp: u64,

        /// Output genesis JSON file path.
        #[arg(long, short, default_value = "genesis.json")]
        output: PathBuf,

        /// Overwrite existing output file.
        #[arg(long)]
        force: bool,
    },

    /// Validate an existing genesis configuration file.
    Validate {
        /// Path to the genesis JSON file to validate.
        #[arg(long, short)]
        input: PathBuf,
    },

    /// Generate a minimal test genesis (4 validators, random keys).
    TestGenesis {
        /// Output genesis JSON file path.
        #[arg(long, short, default_value = "genesis.json")]
        output: PathBuf,

        /// Overwrite existing output file.
        #[arg(long)]
        force: bool,
    },
}

/// Validator public key bundle (as output by `nexus-keygen validator`).
#[derive(Deserialize)]
struct ValidatorPublicKeys {
    falcon_verify_key: String,
    dilithium_verify_key: String,
    kyber_encaps_key: String,
}

// ── Main entry point ─────────────────────────────────────────────────────

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Generate {
            chain_id,
            num_shards,
            stake,
            validator_keys,
            validator_names,
            network_peer_ids,
            timestamp,
            output,
            force,
        } => {
            let params = GenerateParams {
                chain_id,
                num_shards,
                stake,
                validator_keys,
                validator_names,
                network_peer_ids,
                timestamp,
                output,
                force,
            };
            cmd_generate(&params)
        }
        Command::Validate { input } => cmd_validate(&input),
        Command::TestGenesis { output, force } => cmd_test_genesis(&output, force),
    }
}

// ── Command implementations ──────────────────────────────────────────────

struct GenerateParams {
    chain_id: String,
    num_shards: u16,
    stake: u64,
    validator_keys: Vec<PathBuf>,
    validator_names: Vec<String>,
    network_peer_ids: Vec<String>,
    timestamp: u64,
    output: PathBuf,
    force: bool,
}

fn cmd_generate(params: &GenerateParams) -> Result<()> {
    check_overwrite(&params.output, params.force)?;

    if params.network_peer_ids.len() != params.validator_keys.len() {
        anyhow::bail!(
            "--network-peer-id count ({}) must match --validator-keys count ({})",
            params.network_peer_ids.len(),
            params.validator_keys.len()
        );
    }

    let genesis_timestamp = if params.timestamp == 0 {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .context("system clock before Unix epoch")?;
        TimestampMs(now.as_millis() as u64)
    } else {
        TimestampMs(params.timestamp)
    };

    let mut validators = Vec::with_capacity(params.validator_keys.len());

    for (i, key_path) in params.validator_keys.iter().enumerate() {
        let json = fs::read_to_string(key_path)
            .with_context(|| format!("failed to read validator keys: {}", key_path.display()))?;
        let keys: ValidatorPublicKeys = serde_json::from_str(&json)
            .with_context(|| format!("failed to parse validator keys: {}", key_path.display()))?;

        let name = params
            .validator_names
            .get(i)
            .cloned()
            .unwrap_or_else(|| format!("validator-{i}"));

        validators.push(GenesisValidatorEntry {
            name,
            network_peer_id: params.network_peer_ids[i].clone(),
            falcon_verify_key_hex: keys.falcon_verify_key,
            dilithium_verify_key_hex: keys.dilithium_verify_key,
            kyber_encaps_key_hex: keys.kyber_encaps_key,
            stake: Amount(params.stake),
            shard_id: if params.num_shards > 1 {
                Some(ShardId((i as u16) % params.num_shards))
            } else {
                None
            },
        });
    }

    let config = GenesisConfig {
        chain_id: params.chain_id.clone(),
        genesis_timestamp,
        num_shards: params.num_shards,
        validators,
        allocations: Vec::new(),
        consensus: ConsensusConfig::default(),
    };

    config
        .validate()
        .context("generated genesis config failed validation")?;

    write_genesis_json(&config, &params.output)?;

    let n = config.validators.len();
    let f = (n.saturating_sub(1)) / 3;
    eprintln!(
        "Genesis configuration written to {}",
        params.output.display()
    );
    eprintln!("  chain_id:    {}", config.chain_id);
    eprintln!("  validators:  {n} (f={f}, quorum={})", 2 * f + 1);
    eprintln!("  shards:      {}", config.num_shards);
    eprintln!("  timestamp:   {}", config.genesis_timestamp.0);

    Ok(())
}

fn cmd_validate(input: &Path) -> Result<()> {
    let json = fs::read_to_string(input)
        .with_context(|| format!("failed to read genesis file: {}", input.display()))?;
    let config: GenesisConfig = serde_json::from_str(&json)
        .with_context(|| format!("failed to parse genesis file: {}", input.display()))?;

    config.validate().context("genesis validation failed")?;

    let n = config.validators.len();
    let f = (n.saturating_sub(1)) / 3;
    eprintln!("Genesis configuration is VALID");
    eprintln!("  chain_id:      {}", config.chain_id);
    eprintln!("  validators:    {n} (f={f}, quorum={})", 2 * f + 1);
    eprintln!("  shards:        {}", config.num_shards);
    eprintln!("  allocations:   {}", config.allocations.len());
    eprintln!("  total supply:  {}", config.total_supply());

    Ok(())
}

fn cmd_test_genesis(output: &Path, force: bool) -> Result<()> {
    check_overwrite(output, force)?;

    let config = GenesisConfig::for_testing();
    config
        .validate()
        .context("test genesis validation failed")?;

    write_genesis_json(&config, output)?;

    eprintln!("Test genesis written to {}", output.display());
    eprintln!("  chain_id:    {}", config.chain_id);
    eprintln!("  validators:  {}", config.validators.len());

    Ok(())
}

// ── Helpers ──────────────────────────────────────────────────────────────

fn write_genesis_json(config: &GenesisConfig, path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory: {}", parent.display()))?;
        }
    }
    let json =
        serde_json::to_string_pretty(config).context("failed to serialize genesis config")?;
    fs::write(path, &json).with_context(|| format!("failed to write: {}", path.display()))?;
    Ok(())
}

fn check_overwrite(path: &Path, force: bool) -> Result<()> {
    if path.exists() && !force {
        anyhow::bail!(
            "file already exists: {} (use --force to overwrite)",
            path.display()
        );
    }
    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Generate N random libp2p PeerId strings for test genesis configs.
    fn random_peer_ids(n: usize) -> Vec<String> {
        (0..n)
            .map(|_| {
                let kp = libp2p_identity::Keypair::generate_ed25519();
                kp.public().to_peer_id().to_string()
            })
            .collect()
    }

    #[test]
    fn test_test_genesis_command() {
        let dir = TempDir::new().unwrap();
        let output = dir.path().join("genesis.json");
        cmd_test_genesis(&output, false).unwrap();

        assert!(output.exists());
        let json = fs::read_to_string(&output).unwrap();
        let config: GenesisConfig = serde_json::from_str(&json).unwrap();
        config.validate().unwrap();
        assert_eq!(config.validators.len(), 4);
        assert_eq!(config.chain_id, "nexus-test-0");
    }

    #[test]
    fn test_validate_command() {
        let dir = TempDir::new().unwrap();
        let output = dir.path().join("genesis.json");
        cmd_test_genesis(&output, false).unwrap();
        cmd_validate(&output).unwrap();
    }

    #[test]
    fn generate_rejects_mismatched_network_peer_id_count() {
        let params = GenerateParams {
            chain_id: "testnet".into(),
            num_shards: 1,
            stake: 1,
            validator_keys: vec![PathBuf::from("a.json"), PathBuf::from("b.json")],
            validator_names: vec![],
            network_peer_ids: vec!["12D3KooWTestPeer".into()],
            timestamp: 0,
            output: PathBuf::from("genesis.json"),
            force: true,
        };

        let err = cmd_generate(&params).unwrap_err().to_string();
        assert!(err.contains("--network-peer-id count"));
    }

    #[test]
    fn test_validate_invalid_file() {
        let dir = TempDir::new().unwrap();
        let bad_file = dir.path().join("bad.json");
        fs::write(&bad_file, "not json").unwrap();
        let result = cmd_validate(&bad_file);
        assert!(result.is_err());
    }

    #[test]
    fn test_generate_from_key_bundles() {
        use nexus_crypto::{
            DilithiumSigner, FalconSigner, KeyEncapsulationMechanism, KyberKem, Signer,
        };

        let dir = TempDir::new().unwrap();

        // Create 4 validator key bundles (simulating nexus-keygen output).
        let mut key_paths = Vec::new();
        for i in 0..4 {
            let (_, fvk) = FalconSigner::generate_keypair();
            let (_, dvk) = DilithiumSigner::generate_keypair();
            let (kek, _) = KyberKem::generate_keypair();

            let bundle = serde_json::json!({
                "falcon_verify_key": hex::encode(fvk.as_bytes()),
                "dilithium_verify_key": hex::encode(dvk.as_bytes()),
                "kyber_encaps_key": hex::encode(kek.as_bytes()),
            });

            let path = dir.path().join(format!("validator-{i}-public-keys.json"));
            fs::write(&path, serde_json::to_string_pretty(&bundle).unwrap()).unwrap();
            key_paths.push(path);
        }

        let output = dir.path().join("genesis.json");
        cmd_generate(&GenerateParams {
            chain_id: "test-chain".to_owned(),
            num_shards: 2,
            stake: Amount::ONE_NXS.0,
            validator_keys: key_paths.clone(),
            validator_names: vec![],
            network_peer_ids: random_peer_ids(key_paths.len()),
            timestamp: 1000,
            output: output.clone(),
            force: false,
        })
        .unwrap();

        let json = fs::read_to_string(&output).unwrap();
        let config: GenesisConfig = serde_json::from_str(&json).unwrap();
        config.validate().unwrap();
        assert_eq!(config.chain_id, "test-chain");
        assert_eq!(config.validators.len(), 4);
        assert_eq!(config.num_shards, 2);
        assert_eq!(config.genesis_timestamp.0, 1000);
        // With 2 shards, validators should be assigned round-robin.
        assert_eq!(config.validators[0].shard_id, Some(ShardId(0)));
        assert_eq!(config.validators[1].shard_id, Some(ShardId(1)));
        assert_eq!(config.validators[2].shard_id, Some(ShardId(0)));
    }

    #[test]
    fn test_generate_with_custom_names() {
        use nexus_crypto::{
            DilithiumSigner, FalconSigner, KeyEncapsulationMechanism, KyberKem, Signer,
        };

        let dir = TempDir::new().unwrap();
        let mut key_paths = Vec::new();
        for i in 0..4 {
            let (_, fvk) = FalconSigner::generate_keypair();
            let (_, dvk) = DilithiumSigner::generate_keypair();
            let (kek, _) = KyberKem::generate_keypair();
            let bundle = serde_json::json!({
                "falcon_verify_key": hex::encode(fvk.as_bytes()),
                "dilithium_verify_key": hex::encode(dvk.as_bytes()),
                "kyber_encaps_key": hex::encode(kek.as_bytes()),
            });
            let path = dir.path().join(format!("v{i}.json"));
            fs::write(&path, serde_json::to_string_pretty(&bundle).unwrap()).unwrap();
            key_paths.push(path);
        }

        let names = vec![
            "alice".to_owned(),
            "bob".to_owned(),
            "carol".to_owned(),
            "dave".to_owned(),
        ];
        let output = dir.path().join("genesis.json");
        cmd_generate(&GenerateParams {
            chain_id: "named-chain".to_owned(),
            num_shards: 1,
            stake: Amount::ONE_NXS.0,
            validator_keys: key_paths.clone(),
            validator_names: names,
            network_peer_ids: random_peer_ids(key_paths.len()),
            timestamp: 0,
            output: output.clone(),
            force: false,
        })
        .unwrap();

        let config: GenesisConfig =
            serde_json::from_str(&fs::read_to_string(&output).unwrap()).unwrap();
        assert_eq!(config.validators[0].name, "alice");
        assert_eq!(config.validators[3].name, "dave");
    }

    #[test]
    fn test_no_overwrite_without_force() {
        let dir = TempDir::new().unwrap();
        let output = dir.path().join("genesis.json");
        cmd_test_genesis(&output, false).unwrap();
        let result = cmd_test_genesis(&output, false);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already exists"));
    }

    #[test]
    fn test_overwrite_with_force() {
        let dir = TempDir::new().unwrap();
        let output = dir.path().join("genesis.json");
        cmd_test_genesis(&output, false).unwrap();
        cmd_test_genesis(&output, true).unwrap();
    }

    #[test]
    fn test_creates_parent_directory() {
        let dir = TempDir::new().unwrap();
        let output = dir.path().join("nested").join("dir").join("genesis.json");
        cmd_test_genesis(&output, false).unwrap();
        assert!(output.exists());
    }

    #[test]
    fn test_auto_timestamp() {
        use nexus_crypto::{
            DilithiumSigner, FalconSigner, KeyEncapsulationMechanism, KyberKem, Signer,
        };

        let dir = TempDir::new().unwrap();
        let mut key_paths = Vec::new();
        for i in 0..4 {
            let (_, fvk) = FalconSigner::generate_keypair();
            let (_, dvk) = DilithiumSigner::generate_keypair();
            let (kek, _) = KyberKem::generate_keypair();
            let bundle = serde_json::json!({
                "falcon_verify_key": hex::encode(fvk.as_bytes()),
                "dilithium_verify_key": hex::encode(dvk.as_bytes()),
                "kyber_encaps_key": hex::encode(kek.as_bytes()),
            });
            let path = dir.path().join(format!("v{i}.json"));
            fs::write(&path, serde_json::to_string_pretty(&bundle).unwrap()).unwrap();
            key_paths.push(path);
        }

        let output = dir.path().join("genesis.json");
        // timestamp=0 means "use current time"
        cmd_generate(&GenerateParams {
            chain_id: "auto-ts".to_owned(),
            num_shards: 1,
            stake: Amount::ONE_NXS.0,
            validator_keys: key_paths.clone(),
            validator_names: vec![],
            network_peer_ids: random_peer_ids(key_paths.len()),
            timestamp: 0,
            output: output.clone(),
            force: false,
        })
        .unwrap();

        let config: GenesisConfig =
            serde_json::from_str(&fs::read_to_string(&output).unwrap()).unwrap();
        // Timestamp should be recent (within last few seconds).
        assert!(config.genesis_timestamp.0 > 1_000_000_000_000); // after ~2001
    }

    #[test]
    fn test_single_shard_no_assignment() {
        use nexus_crypto::{
            DilithiumSigner, FalconSigner, KeyEncapsulationMechanism, KyberKem, Signer,
        };

        let dir = TempDir::new().unwrap();
        let mut key_paths = Vec::new();
        for i in 0..4 {
            let (_, fvk) = FalconSigner::generate_keypair();
            let (_, dvk) = DilithiumSigner::generate_keypair();
            let (kek, _) = KyberKem::generate_keypair();
            let bundle = serde_json::json!({
                "falcon_verify_key": hex::encode(fvk.as_bytes()),
                "dilithium_verify_key": hex::encode(dvk.as_bytes()),
                "kyber_encaps_key": hex::encode(kek.as_bytes()),
            });
            let path = dir.path().join(format!("v{i}.json"));
            fs::write(&path, serde_json::to_string_pretty(&bundle).unwrap()).unwrap();
            key_paths.push(path);
        }

        let output = dir.path().join("genesis.json");
        cmd_generate(&GenerateParams {
            chain_id: "one-shard".to_owned(),
            num_shards: 1,
            stake: Amount::ONE_NXS.0,
            validator_keys: key_paths.clone(),
            validator_names: vec![],
            network_peer_ids: random_peer_ids(key_paths.len()),
            timestamp: 100,
            output: output.clone(),
            force: false,
        })
        .unwrap();

        let config: GenesisConfig =
            serde_json::from_str(&fs::read_to_string(&output).unwrap()).unwrap();
        // Single shard: no explicit shard assignment needed.
        for v in &config.validators {
            assert!(v.shard_id.is_none());
        }
    }
}
