//! MCP session → ACE session bridge.
//!
//! Maps opaque MCP session identifiers (strings from the LLM client)
//! to internal [`AgentSession`] instances managed by the Agent Core
//! Engine.  The bridge is a thin keying layer — all session lifecycle
//! logic lives in `nexus_intent::agent_core::session`.

use nexus_primitives::Blake3Digest;

// ── Domain tag ──────────────────────────────────────────────────────────

/// Domain tag for MCP session ID derivation.
pub const MCP_SESSION_DOMAIN: &[u8] = b"nexus::mcp::session_bridge::v1";

/// Derive an internal session ID from an opaque MCP session string.
///
/// `BLAKE3(MCP_SESSION_DOMAIN ‖ mcp_session_id_bytes)`
///
/// If no MCP session ID is provided, a random session ID should be
/// generated by the caller.
pub fn derive_session_id(mcp_session_id: &str) -> Blake3Digest {
    let mut hasher = blake3::Hasher::new();
    hasher.update(MCP_SESSION_DOMAIN);
    hasher.update(mcp_session_id.as_bytes());
    let hash: [u8; 32] = *hasher.finalize().as_bytes();
    Blake3Digest(hash)
}

/// Derive a request ID from the MCP session + tool call index.
///
/// `BLAKE3(MCP_SESSION_DOMAIN ‖ "req" ‖ session_id_bytes ‖ LE(index))`
pub fn derive_request_id(session_id: &Blake3Digest, call_index: u64) -> Blake3Digest {
    let mut hasher = blake3::Hasher::new();
    hasher.update(MCP_SESSION_DOMAIN);
    hasher.update(b"req");
    hasher.update(&session_id.0);
    hasher.update(&call_index.to_le_bytes());
    let hash: [u8; 32] = *hasher.finalize().as_bytes();
    Blake3Digest(hash)
}

/// Derive an idempotency key from session + tool name + arguments hash.
///
/// `BLAKE3(MCP_SESSION_DOMAIN ‖ "idem" ‖ session_id ‖ tool_name ‖ args_hash)`
pub fn derive_idempotency_key(
    session_id: &Blake3Digest,
    tool_name: &str,
    args_hash: &Blake3Digest,
) -> Blake3Digest {
    let mut hasher = blake3::Hasher::new();
    hasher.update(MCP_SESSION_DOMAIN);
    hasher.update(b"idem");
    hasher.update(&session_id.0);
    hasher.update(tool_name.as_bytes());
    hasher.update(&args_hash.0);
    let hash: [u8; 32] = *hasher.finalize().as_bytes();
    Blake3Digest(hash)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_id_deterministic() {
        let id1 = derive_session_id("mcp-session-42");
        let id2 = derive_session_id("mcp-session-42");
        assert_eq!(id1, id2);
    }

    #[test]
    fn session_id_varies() {
        let id1 = derive_session_id("session-a");
        let id2 = derive_session_id("session-b");
        assert_ne!(id1, id2);
    }

    #[test]
    fn request_id_deterministic() {
        let sid = derive_session_id("s1");
        let r1 = derive_request_id(&sid, 0);
        let r2 = derive_request_id(&sid, 0);
        assert_eq!(r1, r2);
    }

    #[test]
    fn request_id_varies_by_index() {
        let sid = derive_session_id("s1");
        let r1 = derive_request_id(&sid, 0);
        let r2 = derive_request_id(&sid, 1);
        assert_ne!(r1, r2);
    }

    #[test]
    fn idempotency_key_deterministic() {
        let sid = Blake3Digest([0x01; 32]);
        let args = Blake3Digest([0x02; 32]);
        let k1 = derive_idempotency_key(&sid, "query_balance", &args);
        let k2 = derive_idempotency_key(&sid, "query_balance", &args);
        assert_eq!(k1, k2);
    }

    #[test]
    fn idempotency_key_varies_by_tool() {
        let sid = Blake3Digest([0x01; 32]);
        let args = Blake3Digest([0x02; 32]);
        let k1 = derive_idempotency_key(&sid, "query_balance", &args);
        let k2 = derive_idempotency_key(&sid, "execute_plan", &args);
        assert_ne!(k1, k2);
    }
}
