#!/usr/bin/env bash
# Copyright (c) The Nexus-Node Contributors
# SPDX-License-Identifier: Apache-2.0
# ─────────────────────────────────────────────────────────────────────────
# generate-compose.sh — Generate docker-compose.yml for N validators.
#
# Usage:
#   ./scripts/generate-compose.sh [OPTIONS]
#
# Options:
#   -n NUM_VALIDATORS  Number of validators (default: 7, min: 4)
#   -o OUTPUT          Output file (default: ./docker-compose.yml)
#   -d DEVNET_DIR      Devnet directory mounted by services (default: ./devnet-n7s)
#   -h                 Show help
#
# Environment:
#   NEXUS_NUM_VALIDATORS  Alternative to -n flag (flag takes precedence)
# ─────────────────────────────────────────────────────────────────────────

set -euo pipefail

NUM_VALIDATORS="${NEXUS_NUM_VALIDATORS:-7}"
NUM_SHARDS="${NEXUS_NUM_SHARDS:-2}"
OUTPUT="./docker-compose.yml"
DEVNET_DIR="./devnet-n7s"

while getopts "n:o:d:h" opt; do
    case "$opt" in
        n) NUM_VALIDATORS="$OPTARG" ;;
        o) OUTPUT="$OPTARG" ;;
        d) DEVNET_DIR="$OPTARG" ;;
        h)
            sed -n '/^# Usage:/,/^# ─/p' "$0" | head -n -1 | sed 's/^# //'
            exit 0
            ;;
        *) exit 1 ;;
    esac
done

if [ "$NUM_VALIDATORS" -lt 4 ]; then
    echo "Error: BFT requires at least 4 validators (got $NUM_VALIDATORS)" >&2
    exit 1
fi

# ── Port bases ───────────────────────────────────────────────────────────
REST_BASE=8080
GRPC_BASE=9090
P2P_BASE=7000
DEVNET_SUBNET_PREFIX="172.28.0"
DEVNET_IP_BASE=10

# ── Generate ─────────────────────────────────────────────────────────────
cat > "$OUTPUT" <<'HEADER'
# Copyright (c) The Nexus-Node Contributors
# SPDX-License-Identifier: Apache-2.0
# ─────────────────────────────────────────────────────────────────────────
# Nexus Internal Devnet — docker-compose
#
# Auto-generated by scripts/generate-compose.sh
#
# Prerequisites:
#   1. Build image:    docker build -t nexus-node .
#   2. Bootstrap keys: ./scripts/setup-devnet.sh -n <N> -o <devnet-dir> -f
#   3. Launch:         docker compose up
# ─────────────────────────────────────────────────────────────────────────

HEADER

echo "services:" >> "$OUTPUT"

# ── Validator 0 (bootstrap) ─────────────────────────────────────────────
cat >> "$OUTPUT" <<EOF
  # ── Validator 0 (bootstrap node) ─────────────────────────────────────
  nexus-node-0:
    image: \${NEXUS_IMAGE:-nexus-node}
    container_name: nexus-node-0
    hostname: nexus-node-0
    volumes:
      - ${DEVNET_DIR}/validator-0/config:/nexus/config:ro
      - ${DEVNET_DIR}/validator-0/keys:/nexus/keys:ro
      - ${DEVNET_DIR}/validator-0/data:/nexus/data
    environment:
      - NEXUS_LOG_LEVEL=info
      - NEXUS_GENESIS_PATH=/nexus/config/genesis.json
      - NEXUS_VALIDATOR_KEY_PATH=/nexus/keys
      - NEXUS_STORAGE_PATH=/nexus/data/db
      - NEXUS_NETWORK_PORT=${P2P_BASE}
      - NEXUS_GRPC_PORT=${GRPC_BASE}
      - NEXUS_NUM_SHARDS=${NUM_SHARDS}
    ports:
      - "${REST_BASE}:${REST_BASE}"
      - "${GRPC_BASE}:${GRPC_BASE}"
    networks:
      nexus-devnet:
        ipv4_address: ${DEVNET_SUBNET_PREFIX}.$((DEVNET_IP_BASE + 0))
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:${REST_BASE}/ready || exit 1" ]
      interval: 5s
      timeout: 3s
      start_period: 30s
      retries: 5
EOF

# ── Validators 1..N-1 ───────────────────────────────────────────────────
for i in $(seq 1 $((NUM_VALIDATORS - 1))); do
    REST_PORT=$((REST_BASE + i))
    GRPC_PORT=$((GRPC_BASE + i))
    P2P_PORT=$((P2P_BASE + i))
  NODE_IP="${DEVNET_SUBNET_PREFIX}.$((DEVNET_IP_BASE + i))"

    cat >> "$OUTPUT" <<EOF

  # ── Validator $i ──────────────────────────────────────────────────────
  nexus-node-${i}:
    image: \${NEXUS_IMAGE:-nexus-node}
    container_name: nexus-node-${i}
    hostname: nexus-node-${i}
    depends_on:
      nexus-node-0:
        condition: service_healthy
    volumes:
      - ${DEVNET_DIR}/validator-${i}/config:/nexus/config:ro
      - ${DEVNET_DIR}/validator-${i}/keys:/nexus/keys:ro
      - ${DEVNET_DIR}/validator-${i}/data:/nexus/data
    environment:
      - NEXUS_LOG_LEVEL=info
      - NEXUS_GENESIS_PATH=/nexus/config/genesis.json
      - NEXUS_VALIDATOR_KEY_PATH=/nexus/keys
      - NEXUS_STORAGE_PATH=/nexus/data/db
      - NEXUS_NETWORK_PORT=${P2P_PORT}
      - NEXUS_GRPC_PORT=${GRPC_PORT}
      - NEXUS_NUM_SHARDS=${NUM_SHARDS}
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    networks:
      nexus-devnet:
        ipv4_address: ${NODE_IP}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:${REST_PORT}/ready || exit 1" ]
      interval: 5s
      timeout: 3s
      start_period: 30s
      retries: 5
EOF
done

# ── Network ──────────────────────────────────────────────────────────────
cat >> "$OUTPUT" <<'FOOTER'

networks:
  nexus-devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
FOOTER

echo "Generated $OUTPUT with $NUM_VALIDATORS validators."
